### ISSUE TITLE
How to use Liquid Fill  in your project?

### ISSUE THREAD

**Issue by StephenIII** [vasttian/vue-admin-vuetify#1]
Hey.
I really liked your decision - Liquid Fill (/charts/else). 
Please tell me - how can I use it in my project? 
What files do I need to have in order to make it work for me?

**Comment by vasttian** [comment]
Hey,
You can use the [echarts-liquidfill](https://github.com/ecomfe/echarts-liquidfill) package.
like this: `npm install echarts-liquidfill`
detailed usage can be found in the `src/views/charts/else/charts/LiquidFillChart.vue` file.

**Comment by StephenIII** [comment]
thank you so much
