### ISSUE TITLE
Path error in src/views/widgets/svg-icon/requireIcons.js

### ISSUE THREAD

**Issue by Focus3D** [vasttian/vue-admin-vuetify#2]
Hi,
Could you correct the path in src/views/widgets/svg-icon/requireIcons.js,
replace:
```js
const all = importAll(require.context('@/components/svg-icon/icons', false, /\.svg$/));
```
with:
```js
const all = importAll(require.context('@/components/widgets/svg-icons/icons', false, /\.svg$/));
```

Thank you

**Comment by vasttian** [comment]
Hi Focus3D,
This bug has been fixed, 
I was busy before, but I didn't reply to you in time, sorry.

Thank you.
