### ISSUE TITLE
The up arrow smooth Scroll button does not work on mobile!

### ISSUE THREAD

**Issue by wenewzhang** [vasttian/vue-admin-vuetify#3]
The up arrow smooth Scroll button does not work on mobile!
test on ios & android!

**Comment by vasttian** [comment]
Hi wenewzhang,

This bug has now been fixed.
Modified commit at [85b42be](https://github.com/vasttian/vue-admin-vuetify/commit/f76fa681d8eb65acb8021a243fe23136a0cd5439)

Thx.
